class Constant:
    MAX_FREE_USER_CONTACTS = 10000
    MAX_FREE_USER_BLOCKED_CONTACTS = 100

    MAX_GOLD_USER_CONTACTS = 100000
    MAX_GOLD_USER_BLOCKED_CONTACTS = 1000

    MAX_PLATINUM_USER_CONTACTS = float("inf")
    MAX_PLATINUM_USER_BLOCKED_CONTACTS = 100000

    MAX_COUNT_TO_MARK_GLOBAL_BLOCKED = 1
    MAX_GLOBAL_SPAM_COUNT = 100000